# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='booknote.proto',
  package='booknote',
  serialized_pb='\n\x0e\x62ooknote.proto\x12\x08\x62ooknote\"/\n\x04Head\x12\x0b\n\x03\x63md\x18\x01 \x01(\r\x12\r\n\x05\x65\x63ode\x18\x02 \x01(\r\x12\x0b\n\x03seq\x18\x03 \x01(\r\"]\n\nReqRegiste\x12\x1c\n\x04head\x18\x01 \x02(\x0b\x32\x0e.booknote.Head\x12\x0c\n\x04user\x18\x02 \x02(\t\x12\x0e\n\x06passwd\x18\x03 \x02(\t\x12\x13\n\x0bverify_code\x18\x04 \x02(\t\"J\n\x0cReqUserLogin\x12\x1c\n\x04head\x18\x01 \x02(\x0b\x32\x0e.booknote.Head\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x0e\n\x06passwd\x18\x03 \x01(\t\",\n\x0cResUserLogin\x12\x1c\n\x04head\x18\x01 \x02(\x0b\x32\x0e.booknote.Head*,\n\tErrorCode\x12\x12\n\x05\x45RROR\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x0b\n\x07SUCCESS\x10\x00')

_ERRORCODE = descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='booknote.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='ERROR', index=0, number=-1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=294,
  serialized_end=338,
)


ERROR = -1
SUCCESS = 0



_HEAD = descriptor.Descriptor(
  name='Head',
  full_name='booknote.Head',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='booknote.Head.cmd', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ecode', full_name='booknote.Head.ecode', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='seq', full_name='booknote.Head.seq', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=75,
)


_REQREGISTE = descriptor.Descriptor(
  name='ReqRegiste',
  full_name='booknote.ReqRegiste',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='head', full_name='booknote.ReqRegiste.head', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user', full_name='booknote.ReqRegiste.user', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='passwd', full_name='booknote.ReqRegiste.passwd', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='verify_code', full_name='booknote.ReqRegiste.verify_code', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=77,
  serialized_end=170,
)


_REQUSERLOGIN = descriptor.Descriptor(
  name='ReqUserLogin',
  full_name='booknote.ReqUserLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='head', full_name='booknote.ReqUserLogin.head', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user', full_name='booknote.ReqUserLogin.user', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='passwd', full_name='booknote.ReqUserLogin.passwd', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=172,
  serialized_end=246,
)


_RESUSERLOGIN = descriptor.Descriptor(
  name='ResUserLogin',
  full_name='booknote.ResUserLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='head', full_name='booknote.ResUserLogin.head', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=248,
  serialized_end=292,
)

_REQREGISTE.fields_by_name['head'].message_type = _HEAD
_REQUSERLOGIN.fields_by_name['head'].message_type = _HEAD
_RESUSERLOGIN.fields_by_name['head'].message_type = _HEAD
DESCRIPTOR.message_types_by_name['Head'] = _HEAD
DESCRIPTOR.message_types_by_name['ReqRegiste'] = _REQREGISTE
DESCRIPTOR.message_types_by_name['ReqUserLogin'] = _REQUSERLOGIN
DESCRIPTOR.message_types_by_name['ResUserLogin'] = _RESUSERLOGIN

class Head(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEAD
  
  # @@protoc_insertion_point(class_scope:booknote.Head)

class ReqRegiste(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQREGISTE
  
  # @@protoc_insertion_point(class_scope:booknote.ReqRegiste)

class ReqUserLogin(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUSERLOGIN
  
  # @@protoc_insertion_point(class_scope:booknote.ReqUserLogin)

class ResUserLogin(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESUSERLOGIN
  
  # @@protoc_insertion_point(class_scope:booknote.ResUserLogin)

# @@protoc_insertion_point(module_scope)
